version: '3.8'

services:
  app:
    build:
      context: backend
      dockerfile: docker/dev/Dockerfile
    command: go run .
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
        - action: rebuild
          path: go.mod
    environment:
      - ENV=container-dev
      - PORT=${APP_PORT:-3000}
      - BACKUP_PATH=/home/thaiqu/backup
    ports:
      - "8080:${APP_PORT:-3000}"

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-primary
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-postgres-go}
      POSTGRESQL_CLIENT_MIN_MESSAGES: info
    ports:
      - "5432:5432"

