services:
  backend:
    build:
        context: backend
        dockerfile: ./docker/Dockerfile
    ports:
      - '8082:8082'
    entrypoint: /entrypoint.sh
    environment:
        - ENV=prod
        - PORT=8082
        - BACKUP_PATH=/home/thaiqu/backup
    restart: always
    volumes:
      - backup_data:/app/backup


volumes:
  backup_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/thaiqu/backup