services:
  app:
    container_name: backup-tools
    image: 010497/db-tools:latest
    env_file:
      - .env
    tty: true
    restart: always
    ports:
      - "3022:8080"
    volumes:
      - app-data:/app # Mount a volume to avoid data loss

volumes:
  app-data:
