version: '3.8'

services:
  app:
    build:
      context: backend
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - ENV=container-dev
      - PORT=3001
      - BACKUP_PATH=/home/thaiqu/backup
    ports:
      - "8080:3001"

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-primary
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-postgres-go}
      POSTGRESQL_CLIENT_MIN_MESSAGES: info
    ports:
      - "5432:5432"

