services:
  frontend:
    build:
      context: frontend
      dockerfile: docker/dev/Dockerfile
    container_name: frontend
    command: npm run start
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: package.json
    ports:
      - "4200:4200"
    networks:
      - app_network
  backend:
    build:
      context: backend
      dockerfile: docker/dev/Dockerfile
    command: air
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: go.mod
    restart: unless-stopped
    environment:
      - ENV=container-dev
      - PORT=${APP_PORT:-3000}
      - BACKUP_PATH=/home/thaiqu/backup
    ports:
      - "8080:${APP_PORT:-3000}"
    networks:
      - app_network
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-primary
    networks:
      - app_network
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRESQL_DATABASE: ${POSTGRES_DB:-postgres-go}
      POSTGRESQL_CLIENT_MIN_MESSAGES: info
    ports:
      - "5432:5432"

networks:
  app_network: