# Config file for air
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["*_test.go"]
  delay = 1000
  stop_on_error = true

[log]
  level = "debug"
  color = true
  timestamp = "2006-01-02 15:04:05"
