name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run linter & tests in parallel
        run: |
          npm run lint & \
          npm test & \
          wait
        working-directory: frontend
        
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run tests
        run: go test ./...
        working-directory: backend

  build-and-package:
    runs-on: ubuntu-latest
    needs: [lint-and-test-frontend, test-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Install backend dependencies
        run: go mod download
        working-directory: backend

      - name: Copy frontend build to backend
        run: |
          mkdir -p backend/internal/routes/web
          cp -r frontend/dist/* backend/internal/routes/web/

      - name: Build backend
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o output/main ./cmd/db-tool/main.go
        working-directory: backend

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            backend/output
            frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-package
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.build
          push: true
          tags: 010497/db-tools:latest
          cache-from: type=registry,ref=010497/db-tools:latest
          cache-to: type=inline